#!/bin/sh
#
# Starts RTnet service
#

start() {
	echo -n "Starting RTnet: "
	depmod -a
	for i in rtnet rt_smsc rt_davinci_mdio rt_ticpsw rtpacket rtipv4
	do
	    echo -n "$i "
	    modprobe ${i}
	    sleep 1
	done
	[ $? == 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	echo -n "Stopping RTnet: "
	[ $? == 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
